### ISSUE TITLE
Test code debugging when using testcafe-live

### ISSUE THREAD

**Issue by rafaelchiti** [DevExpress/testcafe-live#13]
Hey! thanks for contributing this lib! I'm evaluating TestCafe / Cypress to adopt it at our company and the live runner makes a big difference (to us)!

Was wondering about debugging 'test code' when running tests through testcafe-live. 
When using testcafe binary we do so by setting the flag `--inspect-brk`. Any way of achieving this with testcafe-live?

Thanks!

**Comment by AndreyBelym** [comment]
Hi @rafaelchiti, currently passing V8 flags is not properly supported. But you can use this easy trick if `testcafe-live` is installed locally (`npm i` without `-g`):
```
node --inspect-brk ./node_modules/testcafe-live/bin/testcafe-live.js chrome test.js
```

It's a bit harder for a global installation, because you have to find out the path to the `testcafe-live` module in the global `node_modules` directory.

**Comment by rafaelchiti** [comment]
oh cool, thanks!!

**Comment by AndreyBelym** [comment]
I close this issue because it became obsolete after merging TestCafe Live into the TestCafe core. Now you can pass the `--inspect` and `--inspect-brk` flags to enable debugging together with the `-L` to enable the Live mode, and Node.js debugging features will be activated correctly due to the `bin-v8-flags-filter` module used by TestCafe binary.
