### ISSUE TITLE
Test run never re-starts despite saying it will

### ISSUE THREAD

**Issue by tnrich** [DevExpress/testcafe-live#31]
Hey there, 
testcafe-live says: 
```
Sources have been changed. Test run is starting...
```
but the tests never actually re-run. 

![image](https://user-images.githubusercontent.com/2730609/48983264-72ba1a00-f0a1-11e8-9e46-0aee3ffca7ad.png)

It is stuck like that forever. Any idea of what is going wrong there?

Thanks

**Comment by hdorgeval** [comment]
Hi @tnrich, I have done  PR #30 to solve this problem. But I am still facing an issue that, I think, can only be solved by the testcafe team.

@AndreyBelym : I know that all testcafe team is very busy at the moment, but, for your information, `testcafe-live` is the only tool we use to create a new test (on a step-by-step approach) and to debug an existing test. The only workaround we found is to stop `testcafe-live` with CTRL+C and then manually restart the command.

It would be great that `testcafe-live` goes back to life as soon as possible.

**Comment by AndreyBelym** [comment]
@hdorgeval, the problem is that we have made a lot of changes to the internal TestCafe logic and structure. TestCafe Live was started as a proof-of-concept project, thus it heavily relies on some TestCafe internals. Your PR solves a different problem - it restores support of globs in TestCafe Live. We need to invest additional time in restoring abilities to restart tests and stay on test pages between test sessions. I'm going to merge your PR for globs as is and try to fix remaining problems in additional PRs.

**Comment by matdurand** [comment]
In the meantime, what versions of testcafe and testcafe-live would work well together?

**Comment by AndreyBelym** [comment]
I can't reproduce the issue with Live mode integrated into `testcafe@1.0.0`: [TestCafe 1.0.0 Released: Live mode](https://devexpress.github.io/testcafe/blog/testcafe-v1-0-0-released.html#live-mode-3215). If you still can reproduce with `testcafe@1.0.0`, please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) in the main TestCafe repository.
